"""Post-hoc trait calibration layer (Phase 3 of variance-compression fix).

The rule-based embedder's [0, 1] clamp caps per-trait std around 0.066 even at
the most aggressive dampening - below the Big Five population norm of ~0.17.
This module implements a **soft rescale** that stretches the observed
distribution toward a target without destroying ordering or distribution shape.

    score_new(t) = clamp01( target_mean +
                            (score_old(t) - obs_mean(t)) *
                            (target_std / obs_std(t)) )

Why soft rescale and NOT z-score:
    z-score gaussifies. Real personality distributions aren't strictly normal
    - they show skew, occasional bimodality from sub-populations. Soft rescale
    is order-preserving and shape-preserving; it just changes the first two
    moments. A tightly-aspected natal chart still produces a proportionally
    stronger trait than a weakly-aspected one.

Stats are adapter-specific AND source-specific. Calibrator with
adapter_type="astrological" loads `config/trait_calibration_astrological.json`;
with adapter_type="big_five" and source="synthetic" (default) it loads
`config/trait_calibration_big_five.json`; with source="real" it loads
`config/trait_calibration_big_five_real.json`. Applying astrological-built
stats to BigFive-derived traits (or vice versa) structurally distorts them
because the raw distributions are different; applying synthetic-built stats
to a real-population BigFive run likewise mis-centers traits because real
IPIP-NEO-300 means sit ~0.68 vs synth 0.50. See
`outputs/bf_validity_study_real.md` §9.

Limits acknowledged:
    If the stretch factor is large (target_std >> obs_std), soft rescale will
    push outlier agents outside [0, 1]; clamp01 at the end catches that, so
    calibration can still introduce saturation at the tails. Validation
    (Phase 4) measures how much.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from realm.core.config import load_astrology_config
from realm.core.logging import get_logger

from .trait_vector import TraitVector

logger = get_logger(__name__)


@dataclass(frozen=True, slots=True)
class CalibrationStats:
    """Observed (mean, std) per trait on the source population."""

    per_trait: Mapping[str, tuple[float, float]]

    @classmethod
    def from_json(cls, path: str | Path) -> CalibrationStats:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        stats = {k: (float(v[0]), float(v[1])) for k, v in data["per_trait"].items()}
        return cls(per_trait=stats)

    def to_json(self, path: str | Path) -> None:
        payload = {
            "per_trait": {k: [m, s] for k, (m, s) in self.per_trait.items()},
            "_note": (
                "Generated by scripts/build_calibration_stats.py. Regenerate "
                "any time dampening, planet_trait_map, sign_modifiers, or "
                "the BigFive derivation table change."
            ),
        }
        Path(path).write_text(
            json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8",
        )


class TraitCalibrator:
    """Config-driven wrapper around calibrate().

    Reads astrology.yaml -> astrology.trait_calibration. When enabled, loads
    stats from a JSON file selected via (in priority order):
      1. explicit `stats_path` constructor arg
      2. `adapter_type` + `source` args -> derives a repo-relative path:
         - source in (None, "synthetic"): `config/trait_calibration_{type}.json`
         - source="real" (or other tag): `config/trait_calibration_{type}_{source}.json`
      3. `astrology.yaml`'s `trait_calibration.stats_path` key

    `source` defaults to the `trait_calibration.source` key in astrology.yaml
    if not set explicitly; if that key is missing too it falls back to
    "synthetic" (backward-compatible).

    When disabled or stats file missing, apply() is an identity pass-through.
    """

    def __init__(
        self,
        enabled: bool | None = None,
        target_mean: float | None = None,
        target_std: float | None = None,
        stats_path: str | Path | None = None,
        adapter_type: str | None = None,
        source: str | None = None,
    ) -> None:
        cfg = {}
        try:
            cfg = (
                load_astrology_config()
                .get("astrology", {})
                .get("trait_calibration", {})
            )
        except Exception:
            cfg = {}
        self._enabled = bool(cfg.get("enabled", False)) if enabled is None else enabled
        self._target_mean = (
            float(cfg.get("target_mean", 0.50))
            if target_mean is None
            else target_mean
        )
        self._target_std = (
            float(cfg.get("target_std", 0.17))
            if target_std is None
            else target_std
        )
        resolved_source = (
            source
            if source is not None
            else cfg.get("source", "synthetic")
        )
        # Resolve stats_path with priority: explicit -> adapter_type -> config
        resolved: Path | None = None
        if stats_path is not None:
            resolved = Path(stats_path).resolve()
        elif adapter_type is not None:
            repo_root = Path(__file__).resolve().parent.parent.parent
            base = f"trait_calibration_{adapter_type}"
            if resolved_source and resolved_source != "synthetic":
                base = f"{base}_{resolved_source}"
            resolved = repo_root / "config" / f"{base}.json"
        elif cfg.get("stats_path"):
            resolved = Path(cfg["stats_path"]).resolve()
        self._stats_path = resolved
        self._adapter_type = adapter_type
        self._source = resolved_source
        self._stats: CalibrationStats | None = None
        if self._enabled:
            if self._stats_path is None or not self._stats_path.exists():
                logger.warning(
                    "TraitCalibrator enabled but stats_path missing (%s, "
                    "adapter_type=%s); falling back to identity.",
                    self._stats_path, adapter_type,
                )
                self._enabled = False
            else:
                self._stats = CalibrationStats.from_json(self._stats_path)

    @property
    def enabled(self) -> bool:
        return self._enabled

    @property
    def adapter_type(self) -> str | None:
        return self._adapter_type

    @property
    def source(self) -> str | None:
        return self._source

    @property
    def stats_path(self) -> Path | None:
        return self._stats_path

    def apply(self, traits: TraitVector) -> TraitVector:
        if not self._enabled or self._stats is None:
            return traits
        return calibrate(
            traits,
            self._stats,
            target_mean=self._target_mean,
            target_std=self._target_std,
        )


def calibrate(
    vector: TraitVector,
    stats: CalibrationStats,
    target_mean: float = 0.50,
    target_std: float = 0.17,
    min_obs_std: float = 1e-4,
) -> TraitVector:
    """Soft-rescale each trait toward (target_mean, target_std).

    If a trait's observed std is below `min_obs_std`, leave it alone - there
    is no variance to stretch (degenerate case; population is essentially
    constant on that trait).
    """
    updated: dict[str, float] = {}
    for trait in TraitVector.trait_names():
        obs = stats.per_trait.get(trait)
        if obs is None:
            updated[trait] = getattr(vector, trait)
            continue
        obs_mean, obs_std = obs
        if obs_std < min_obs_std:
            updated[trait] = getattr(vector, trait)
            continue
        old_val = getattr(vector, trait)
        scale = target_std / obs_std
        new_val = target_mean + (old_val - obs_mean) * scale
        updated[trait] = max(0.0, min(1.0, new_val))
    return TraitVector.from_dict(updated)
